- name: configuration interfaces

  hosts: csr1000

  gather_facts: false

  tasks:

    - name: configgure les interfaces

      cisco.ios.ios_l3_interfaces:

        config:

        - name: GigabitEthernet2

          ipv4:

          - address: 192.168.2.1/24

        - name: GigabitEthernet3

          ipv4: 

          - address: 192.168.3.1/24

        - name: GigabitEthernet4

          ipv4: 

          - address: 192.168.4.1/24

        state: merged
