- name: Configuration DHCP 

  hosts: csr1000

  gather_facts: no

  tasks:

    - name: supprime le DHCP existant

      cisco.ios.ios_config:

        lines:

          - no ip dhcp pool MY_POOL

      ignore_errors: yes

    - name: Configuration pool DHCP 

      cisco.ios.ios_config:
        lines:
          - ip dhcp excluded-address 162.3.32.1
          - ip dhcp pool MY_POOL
          - network 162.3.32.0 255.255.254.0
          - default-router 162.3.32.1
          - exit


    - name: enregitrement de la configuration

      cisco.ios.ios_command:

        commands:

          - write memory

